/*
    Declares functions for maze generation
*/

#include <vector>

/*********************************************************************************
 * @brief Returns a uniform spanning tree maze generated by the Aldous-Broder 
 *        algorithm.
 *
 *  @param size dictates size of the generated maze (min 2, max 99)
 *  @returns size*size uniform spanning tree maze
 *********************************************************************************/
extern std::vector<std::vector<int>> createMaze(const int size, int *pos);